import { SmoothieDto } from './smoothie.types';

export const SMOOTHIE_SEED: SmoothieDto[] = [
  {
    id: 'green-power',
    name: 'Green Power',
    description: 'Espinaca, manzana verde, jengibre y lima. Lleno de vitaminas.',
    category: 'Detox',
    ingredients: ['Espinaca', 'Manzana verde', 'Jengibre', 'Lima'],
    price: 85,
    calories: 120,
    prepMinutes: 4,
    popular: false,
    favorite: false,
    active: true,
    imagePreset: 'green-power'
  },
  {
    id: 'berry-blast',
    name: 'Berry Blast',
    description: 'Mezcla de moras, arandanos y frambuesas con yogur griego.',
    category: 'Clasicos',
    ingredients: ['Moras', 'Arandanos', 'Frambuesas', 'Yogur griego'],
    price: 95,
    calories: 180,
    prepMinutes: 3,
    popular: true,
    favorite: true,
    active: true,
    imagePreset: 'berry-blast'
  },
  {
    id: 'tropical-sunset',
    name: 'Tropical Sunset',
    description: 'Mango, pina, coco y un toque de curcuma. Puro paraiso.',
    category: 'Tropicales',
    ingredients: ['Mango', 'Pina', 'Leche de coco', 'Curcuma'],
    price: 90,
    calories: 200,
    prepMinutes: 4,
    popular: true,
    favorite: false,
    active: true,
    imagePreset: 'tropical-sunset'
  },
  {
    id: 'fresa-paradise',
    name: 'Fresa Paradise',
    description: 'Fresas frescas, platano y leche de almendra. Clasico favorito.',
    category: 'Clasicos',
    ingredients: ['Fresas', 'Platano', 'Leche de almendra', 'Vainilla'],
    price: 80,
    calories: 165,
    prepMinutes: 4,
    popular: false,
    favorite: false,
    active: true,
    imagePreset: 'fresa-paradise'
  },
  {
    id: 'golden-protein',
    name: 'Golden Protein',
    description: 'Avena, datil, crema de mani y proteina vainilla para arrancar fuerte.',
    category: 'Proteina',
    ingredients: ['Avena', 'Datil', 'Proteina vainilla', 'Crema de mani'],
    price: 110,
    calories: 320,
    prepMinutes: 5,
    popular: true,
    favorite: false,
    active: true,
    imagePreset: 'golden-protein'
  },
  {
    id: 'blue-lagoon',
    name: 'Blue Lagoon',
    description: 'Pina, pepino y spirulina azul. Fresco, ligero y brillante.',
    category: 'Detox',
    ingredients: ['Pina', 'Pepino', 'Spirulina azul', 'Agua de coco'],
    price: 88,
    calories: 90,
    prepMinutes: 3,
    popular: false,
    favorite: true,
    active: true,
    imagePreset: 'blue-lagoon'
  },
  {
    id: 'cacao-rush',
    name: 'Cacao Rush',
    description: 'Cacao, cafe frio, banana y leche de avena. Energia cremosa.',
    category: 'Proteina',
    ingredients: ['Cacao', 'Cafe frio', 'Banana', 'Leche de avena'],
    price: 102,
    calories: 240,
    prepMinutes: 4,
    popular: false,
    favorite: false,
    active: false,
    imagePreset: 'cacao-rush'
  }
];
